//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlyT.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnlyT.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access code.
        /// </summary>
        public static string ACCESS_CODE {
            get {
                return ResourceManager.GetString("ACCESS_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bell is active.
        /// </summary>
        public static string ACTIVE_BELL {
            get {
                return ResourceManager.GetString("ACTIVE_BELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midweek adaptive mode.
        /// </summary>
        public static string ADAPTIVE_MIDWEEK {
            get {
                return ResourceManager.GetString("ADAPTIVE_MIDWEEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string ADAPTIVE_MODE_NONE {
            get {
                return ResourceManager.GetString("ADAPTIVE_MODE_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-way.
        /// </summary>
        public static string ADAPTIVE_MODE_ONE_WAY {
            get {
                return ResourceManager.GetString("ADAPTIVE_MODE_ONE_WAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-way.
        /// </summary>
        public static string ADAPTIVE_MODE_TWO_WAY {
            get {
                return ResourceManager.GetString("ADAPTIVE_MODE_TWO_WAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekend adaptive mode.
        /// </summary>
        public static string ADAPTIVE_WEEKEND {
            get {
                return ResourceManager.GetString("ADAPTIVE_WEEKEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow count-up toggle.
        /// </summary>
        public static string ALLOW_COUNT_UP_TOGGLE {
            get {
                return ResourceManager.GetString("ALLOW_COUNT_UP_TOGGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always on top.
        /// </summary>
        public static string ALWAYS_ON_TOP {
            get {
                return ResourceManager.GetString("ALWAYS_ON_TOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysing meeting timer data.
        /// </summary>
        public static string ANALYSING_REPORT_DATA {
            get {
                return ResourceManager.GetString("ANALYSING_REPORT_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software version {0}.
        /// </summary>
        public static string APP_VER {
            get {
                return ResourceManager.GetString("APP_VER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REMOTE APPS.
        /// </summary>
        public static string APPS_SECTION {
            get {
                return ResourceManager.GetString("APPS_SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically sound.
        /// </summary>
        public static string AUTO_BELL {
            get {
                return ResourceManager.GetString("AUTO_BELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTOMATIC MODE.
        /// </summary>
        public static string AUTO_SECTION {
            get {
                return ResourceManager.GetString("AUTO_SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BELL.
        /// </summary>
        public static string BELL_SECTION {
            get {
                return ResourceManager.GetString("BELL_SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circuit visit.
        /// </summary>
        public static string CIRCUIT_VISIT {
            get {
                return ResourceManager.GetString("CIRCUIT_VISIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [circuit visit].
        /// </summary>
        public static string CIRCUIT_VISIT_BRACKETS {
            get {
                return ResourceManager.GetString("CIRCUIT_VISIT_BRACKETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock background gradient.
        /// </summary>
        public static string CLOCK_BACKGROUND_COLOUR {
            get {
                return ResourceManager.GetString("CLOCK_BACKGROUND_COLOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12-hour.
        /// </summary>
        public static string CLOCK_FORMAT_12 {
            get {
                return ResourceManager.GetString("CLOCK_FORMAT_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12-hour (am/pm).
        /// </summary>
        public static string CLOCK_FORMAT_12AMPM {
            get {
                return ResourceManager.GetString("CLOCK_FORMAT_12AMPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12-hour (leading zero).
        /// </summary>
        public static string CLOCK_FORMAT_12Z {
            get {
                return ResourceManager.GetString("CLOCK_FORMAT_12Z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12-hour (leading zero &amp; am/pm).
        /// </summary>
        public static string CLOCK_FORMAT_12ZAMPM {
            get {
                return ResourceManager.GetString("CLOCK_FORMAT_12ZAMPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24-hour.
        /// </summary>
        public static string CLOCK_FORMAT_24 {
            get {
                return ResourceManager.GetString("CLOCK_FORMAT_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24-hour (leading zero).
        /// </summary>
        public static string CLOCK_FORMAT_24Z {
            get {
                return ResourceManager.GetString("CLOCK_FORMAT_24Z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEB CLOCK.
        /// </summary>
        public static string CLOCK_SECTION {
            get {
                return ResourceManager.GetString("CLOCK_SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html style=&quot;display:block; height:100%; margin:0; padding:0&quot;&gt;
        ///	&lt;head&gt;
        ///		&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;/&gt;		
        ///		&lt;title&gt;OnlyT Clock&lt;/title&gt;
        ///		&lt;style type=&quot;text/css&quot;&gt;			
        ///			html 
        ///			{
        ///				font-family: sans-serif;
        ///				background: #000000;
        ///			}
        ///			.clockstyle 
        ///			{
        ///				font-family: sans-serif;
        ///				font-weight: bold;
        ///				color: #FFFFFF;
        ///			}
        ///			.clockstyle_yellow
        ///			{
        ///				font-family: sans-serif;
        ///				font-weight: bold;
        ///				color: #FFFF66;
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ClockHtmlTemplate {
            get {
                return ResourceManager.GetString("ClockHtmlTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLOSE COUNTDOWN.
        /// </summary>
        public static string CLOSE_COUNTDOWN {
            get {
                return ResourceManager.GetString("CLOSE_COUNTDOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Countdown Window.
        /// </summary>
        public static string CLOSE_COUNTDOWN_TOOLTIP {
            get {
                return ResourceManager.GetString("CLOSE_COUNTDOWN_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circuit visit toggle.
        /// </summary>
        public static string CO_VISIT_TOGGLE {
            get {
                return ResourceManager.GetString("CO_VISIT_TOGGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concluding Segment.
        /// </summary>
        public static string CONCLUDING_SEGMENT {
            get {
                return ResourceManager.GetString("CONCLUDING_SEGMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note that the monitor is controlled by a command-line setting.
        /// </summary>
        public static string CONTROLLED_BY_CMD_LINE {
            get {
                return ResourceManager.GetString("CONTROLLED_BY_CMD_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration (mins).
        /// </summary>
        public static string COUNTDOWN_DURATION_MINS {
            get {
                return ResourceManager.GetString("COUNTDOWN_DURATION_MINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements.
        /// </summary>
        public static string COUNTDOWN_ELEMENTS {
            get {
                return ResourceManager.GetString("COUNTDOWN_ELEMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windowed.
        /// </summary>
        public static string COUNTDOWN_IS_WINDOWED {
            get {
                return ResourceManager.GetString("COUNTDOWN_IS_WINDOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEETING COUNTDOWN.
        /// </summary>
        public static string COUNTDOWN_SECTION {
            get {
                return ResourceManager.GetString("COUNTDOWN_SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open transparent &quot;windowed&quot; countdown.
        /// </summary>
        public static string COUNTDOWN_STYLE_CONFLICT {
            get {
                return ResourceManager.GetString("COUNTDOWN_STYLE_CONFLICT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparent background.
        /// </summary>
        public static string COUNTDOWN_TRANSPARENT {
            get {
                return ResourceManager.GetString("COUNTDOWN_TRANSPARENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom level:.
        /// </summary>
        public static string COUNTDOWN_ZOOM {
            get {
                return ResourceManager.GetString("COUNTDOWN_ZOOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently counting down.
        /// </summary>
        public static string COUNTING_DOWN {
            get {
                return ResourceManager.GetString("COUNTING_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently counting up.
        /// </summary>
        public static string COUNTING_UP {
            get {
                return ResourceManager.GetString("COUNTING_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create folder {0}.
        /// </summary>
        public static string CREATE_FOLDER_ERROR {
            get {
                return ResourceManager.GetString("CREATE_FOLDER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dial.
        /// </summary>
        public static string DIAL {
            get {
                return ResourceManager.GetString("DIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dial and digital.
        /// </summary>
        public static string DIAL_AND_DIGITAL {
            get {
                return ResourceManager.GetString("DIAL_AND_DIGITAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital.
        /// </summary>
        public static string DIGITAL {
            get {
                return ResourceManager.GetString("DIGITAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital clock format.
        /// </summary>
        public static string DIGITAL_CLOCK_FORMAT {
            get {
                return ResourceManager.GetString("DIGITAL_CLOCK_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapted duration.
        /// </summary>
        public static string DURATION_ADAPTED {
            get {
                return ResourceManager.GetString("DURATION_ADAPTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified duration.
        /// </summary>
        public static string DURATION_MODIFIED {
            get {
                return ResourceManager.GetString("DURATION_MODIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original duration.
        /// </summary>
        public static string DURATION_ORIGINAL {
            get {
                return ResourceManager.GetString("DURATION_ORIGINAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string ENABLED {
            get {
                return ResourceManager.GetString("ENABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string ENABLED_API {
            get {
                return ResourceManager.GetString("ENABLED_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string ENABLED_BELL {
            get {
                return ResourceManager.GetString("ENABLED_BELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string ENABLED_WEB_CLOCK {
            get {
                return ResourceManager.GetString("ENABLED_WEB_CLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat clock.
        /// </summary>
        public static string FLAT_CLOCK {
            get {
                return ResourceManager.GetString("FLAT_CLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analogue.
        /// </summary>
        public static string FULL_SCREEN_ANALOGUE {
            get {
                return ResourceManager.GetString("FULL_SCREEN_ANALOGUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analogue and Digital.
        /// </summary>
        public static string FULL_SCREEN_BOTH {
            get {
                return ResourceManager.GetString("FULL_SCREEN_BOTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full-screen clock mode.
        /// </summary>
        public static string FULL_SCREEN_CLOCK {
            get {
                return ResourceManager.GetString("FULL_SCREEN_CLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital.
        /// </summary>
        public static string FULL_SCREEN_DIGITAL {
            get {
                return ResourceManager.GetString("FULL_SCREEN_DIGITAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated timing report.
        /// </summary>
        public static string GENERATING_REPORT {
            get {
                return ResourceManager.GetString("GENERATING_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HELP {
            get {
                return ResourceManager.GetString("HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bell is inactive.
        /// </summary>
        public static string INACTIVE_BELL {
            get {
                return ResourceManager.GetString("INACTIVE_BELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interim Segment.
        /// </summary>
        public static string INTERIM_SEGMENT {
            get {
                return ResourceManager.GetString("INTERIM_SEGMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introductory Segment.
        /// </summary>
        public static string INTRO_SEGMENT {
            get {
                return ResourceManager.GetString("INTRO_SEGMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP address.
        /// </summary>
        public static string IP_ADDRESS {
            get {
                return ResourceManager.GetString("IP_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JW Library® compatibility mode.
        /// </summary>
        public static string JW_COMPAT_MODE {
            get {
                return ResourceManager.GetString("JW_COMPAT_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;JW Library&quot; is a registered trademark of Watch Tower Bible and Tract Society of Pennsylvania.
        /// </summary>
        public static string JWL_TRADEMARK {
            get {
                return ResourceManager.GetString("JWL_TRADEMARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string LOCATION_ON_SCREEN {
            get {
                return ResourceManager.GetString("LOCATION_ON_SCREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string LOG_LEVEL_DEBUG {
            get {
                return ResourceManager.GetString("LOG_LEVEL_DEBUG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string LOG_LEVEL_ERROR {
            get {
                return ResourceManager.GetString("LOG_LEVEL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal.
        /// </summary>
        public static string LOG_LEVEL_FATAL {
            get {
                return ResourceManager.GetString("LOG_LEVEL_FATAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string LOG_LEVEL_INFORMATION {
            get {
                return ResourceManager.GetString("LOG_LEVEL_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbose.
        /// </summary>
        public static string LOG_LEVEL_VERBOSE {
            get {
                return ResourceManager.GetString("LOG_LEVEL_VERBOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string LOG_LEVEL_WARNING {
            get {
                return ResourceManager.GetString("LOG_LEVEL_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging level.
        /// </summary>
        public static string LOGGING_LEVEL {
            get {
                return ResourceManager.GetString("LOGGING_LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAIN.
        /// </summary>
        public static string MAIN_SECTION {
            get {
                return ResourceManager.GetString("MAIN_SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual mode.
        /// </summary>
        public static string MANUAL_MODE {
            get {
                return ResourceManager.GetString("MANUAL_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting.
        /// </summary>
        public static string MEETING {
            get {
                return ResourceManager.GetString("MEETING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting start times (1 per line).
        /// </summary>
        public static string MEETING_STARTS {
            get {
                return ResourceManager.GetString("MEETING_STARTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midweek.
        /// </summary>
        public static string MIDWEEK {
            get {
                return ResourceManager.GetString("MIDWEEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ministry - Item 1.
        /// </summary>
        public static string MINISTRY1 {
            get {
                return ResourceManager.GetString("MINISTRY1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ministry - Item 2.
        /// </summary>
        public static string MINISTRY2 {
            get {
                return ResourceManager.GetString("MINISTRY2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ministry - Item 3.
        /// </summary>
        public static string MINISTRY3 {
            get {
                return ResourceManager.GetString("MINISTRY3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ministry - Item 4.
        /// </summary>
        public static string MINISTRY4 {
            get {
                return ResourceManager.GetString("MINISTRY4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MISCELLANEOUS.
        /// </summary>
        public static string MISC_SECTION {
            get {
                return ResourceManager.GetString("MISC_SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor.
        /// </summary>
        public static string MONITOR {
            get {
                return ResourceManager.GetString("MONITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windowed.
        /// </summary>
        public static string MONITOR_IS_WINDOWED {
            get {
                return ResourceManager.GetString("MONITOR_IS_WINDOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string MONITOR_NONE {
            get {
                return ResourceManager.GetString("MONITOR_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show mouse pointer.
        /// </summary>
        public static string MOUSE_PTR {
            get {
                return ResourceManager.GetString("MOUSE_PTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put each start time on a new line..
        /// </summary>
        public static string MTG_START_NOTES1 {
            get {
                return ResourceManager.GetString("MTG_START_NOTES1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use any time format you like!.
        /// </summary>
        public static string MTG_START_NOTES2 {
            get {
                return ResourceManager.GetString("MTG_START_NOTES2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optionally include a day, e.g. &quot;Thu 19:15&quot;.
        /// </summary>
        public static string MTG_START_NOTES3 {
            get {
                return ResourceManager.GetString("MTG_START_NOTES3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available!.
        /// </summary>
        public static string NEW_VERSION {
            get {
                return ResourceManager.GetString("NEW_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report NOT generated!.
        /// </summary>
        public static string NO_REPORT {
            get {
                return ResourceManager.GetString("NO_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings disabled by administrator!.
        /// </summary>
        public static string NOT_AVAIL_ADMIN {
            get {
                return ResourceManager.GetString("NOT_AVAIL_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings not available while timer is running!.
        /// </summary>
        public static string NOT_AVAIL_TIMER_RUNNING {
            get {
                return ResourceManager.GetString("NOT_AVAIL_TIMER_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes:.
        /// </summary>
        public static string NOTES {
            get {
                return ResourceManager.GetString("NOTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string OP_MODE {
            get {
                return ResourceManager.GetString("OP_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        public static string OP_MODE_AUTO {
            get {
                return ResourceManager.GetString("OP_MODE_AUTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File-based.
        /// </summary>
        public static string OP_MODE_FILE {
            get {
                return ResourceManager.GetString("OP_MODE_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string OP_MODE_MANUAL {
            get {
                return ResourceManager.GetString("OP_MODE_MANUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPEN PORT.
        /// </summary>
        public static string OPEN_PORT {
            get {
                return ResourceManager.GetString("OPEN_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persist student time.
        /// </summary>
        public static string PERSIST_STUDENT_TIME {
            get {
                return ResourceManager.GetString("PERSIST_STUDENT_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persist talk duration.
        /// </summary>
        public static string PERSIST_TALK_DURATION {
            get {
                return ResourceManager.GetString("PERSIST_TALK_DURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string PORT {
            get {
                return ResourceManager.GetString("PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open the port (see log)!.
        /// </summary>
        public static string PORT_OPEN_FAILED {
            get {
                return ResourceManager.GetString("PORT_OPEN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port opened and reservation made.
        /// </summary>
        public static string PORT_OPENED {
            get {
                return ResourceManager.GetString("PORT_OPENED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REMOTE ACCESS.
        /// </summary>
        public static string REMOTE_SECTION {
            get {
                return ResourceManager.GetString("REMOTE_SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart OnlyT after changing the language..
        /// </summary>
        public static string RESTART_LANGUAGE {
            get {
                return ResourceManager.GetString("RESTART_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        public static string SCREEN_LOCATION_BOTTOM {
            get {
                return ResourceManager.GetString("SCREEN_LOCATION_BOTTOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom left.
        /// </summary>
        public static string SCREEN_LOCATION_BOTTOM_LEFT {
            get {
                return ResourceManager.GetString("SCREEN_LOCATION_BOTTOM_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom right.
        /// </summary>
        public static string SCREEN_LOCATION_BOTTOM_RIGHT {
            get {
                return ResourceManager.GetString("SCREEN_LOCATION_BOTTOM_RIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre.
        /// </summary>
        public static string SCREEN_LOCATION_CENTRE {
            get {
                return ResourceManager.GetString("SCREEN_LOCATION_CENTRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string SCREEN_LOCATION_LEFT {
            get {
                return ResourceManager.GetString("SCREEN_LOCATION_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string SCREEN_LOCATION_RIGHT {
            get {
                return ResourceManager.GetString("SCREEN_LOCATION_RIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string SCREEN_LOCATION_TOP {
            get {
                return ResourceManager.GetString("SCREEN_LOCATION_TOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top left.
        /// </summary>
        public static string SCREEN_LOCATION_TOP_LEFT {
            get {
                return ResourceManager.GetString("SCREEN_LOCATION_TOP_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top right.
        /// </summary>
        public static string SCREEN_LOCATION_TOP_RIGHT {
            get {
                return ResourceManager.GetString("SCREEN_LOCATION_TOP_RIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Living.
        /// </summary>
        public static string SECTION_LIVING {
            get {
                return ResourceManager.GetString("SECTION_LIVING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ministry.
        /// </summary>
        public static string SECTION_MINISTRY {
            get {
                return ResourceManager.GetString("SECTION_MINISTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treasures.
        /// </summary>
        public static string SECTION_TREASURES {
            get {
                return ResourceManager.GetString("SECTION_TREASURES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekend.
        /// </summary>
        public static string SECTION_WEEKEND {
            get {
                return ResourceManager.GetString("SECTION_WEEKEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show sector on analogue clock.
        /// </summary>
        public static string SECTOR_ANALOG_CLOCK {
            get {
                return ResourceManager.GetString("SECTOR_ANALOG_CLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SETTINGS {
            get {
                return ResourceManager.GetString("SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate reports.
        /// </summary>
        public static string SHOULD_GENERATE_REPORTS {
            get {
                return ResourceManager.GetString("SHOULD_GENERATE_REPORTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock frame.
        /// </summary>
        public static string SHOW_CLOCK_FRAME {
            get {
                return ResourceManager.GetString("SHOW_CLOCK_FRAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show frame.
        /// </summary>
        public static string SHOW_COUNTDOWN_FRAME {
            get {
                return ResourceManager.GetString("SHOW_COUNTDOWN_FRAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show seconds.
        /// </summary>
        public static string SHOW_SECONDS {
            get {
                return ResourceManager.GetString("SHOW_SECONDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer frame.
        /// </summary>
        public static string SHOW_TIMER_FRAME {
            get {
                return ResourceManager.GetString("SHOW_TIMER_FRAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound the bell.
        /// </summary>
        public static string SOUND_BELL {
            get {
                return ResourceManager.GetString("SOUND_BELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split-screen width:.
        /// </summary>
        public static string SPLIT_WIDTH {
            get {
                return ResourceManager.GetString("SPLIT_WIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concluding Talk.
        /// </summary>
        public static string TALK_CONCLUDING {
            get {
                return ResourceManager.GetString("TALK_CONCLUDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concluding Comments.
        /// </summary>
        public static string TALK_CONCLUDING_COMMENTS {
            get {
                return ResourceManager.GetString("TALK_CONCLUDING_COMMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congregation Bible Study.
        /// </summary>
        public static string TALK_CONG_STUDY {
            get {
                return ResourceManager.GetString("TALK_CONG_STUDY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digging for Spiritual Gems.
        /// </summary>
        public static string TALK_DIGGING {
            get {
                return ResourceManager.GetString("TALK_DIGGING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Living - Part 1.
        /// </summary>
        public static string TALK_LIVING1 {
            get {
                return ResourceManager.GetString("TALK_LIVING1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Living - Part 2.
        /// </summary>
        public static string TALK_LIVING2 {
            get {
                return ResourceManager.GetString("TALK_LIVING2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Comments.
        /// </summary>
        public static string TALK_OPENING_COMMENTS {
            get {
                return ResourceManager.GetString("TALK_OPENING_COMMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Month&apos;s Presentations.
        /// </summary>
        public static string TALK_PRESENTATIONS {
            get {
                return ResourceManager.GetString("TALK_PRESENTATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Talk.
        /// </summary>
        public static string TALK_PUBLIC {
            get {
                return ResourceManager.GetString("TALK_PUBLIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bible Reading.
        /// </summary>
        public static string TALK_READING {
            get {
                return ResourceManager.GetString("TALK_READING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Talk.
        /// </summary>
        public static string TALK_SERVICE {
            get {
                return ResourceManager.GetString("TALK_SERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treasures Talk.
        /// </summary>
        public static string TALK_TREASURES {
            get {
                return ResourceManager.GetString("TALK_TREASURES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watchtower Study.
        /// </summary>
        public static string TALK_WT {
            get {
                return ResourceManager.GetString("TALK_WT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string TEST {
            get {
                return ResourceManager.GetString("TEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throttled.
        /// </summary>
        public static string THROTTLED {
            get {
                return ResourceManager.GetString("THROTTLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease.
        /// </summary>
        public static string TIME_DECREASE {
            get {
                return ResourceManager.GetString("TIME_DECREASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase.
        /// </summary>
        public static string TIME_INCREASE {
            get {
                return ResourceManager.GetString("TIME_INCREASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time of day under timer.
        /// </summary>
        public static string TIME_UNDER_TIMER {
            get {
                return ResourceManager.GetString("TIME_UNDER_TIMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer background gradient.
        /// </summary>
        public static string TIMER_BACKGROUND_COLOUR {
            get {
                return ResourceManager.GetString("TIMER_BACKGROUND_COLOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer counts up.
        /// </summary>
        public static string TIMER_COUNT_UP {
            get {
                return ResourceManager.GetString("TIMER_COUNT_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMER WINDOW.
        /// </summary>
        public static string TIMER_WIN_SECTION {
            get {
                return ResourceManager.GetString("TIMER_WIN_SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///    &lt;title&gt;OnlyT Timers&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        html {
        ///            font-family: sans-serif;
        ///            background: #000000;
        ///            display: block;
        ///            height: 100%;
        ///            margin: 0;
        ///            padding: 0;
        ///        }
        ///
        ///        body {
        ///            display: table;
        ///            width [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TimersHtmlTemplate {
            get {
                return ResourceManager.GetString("TimersHtmlTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIEW.
        /// </summary>
        public static string VIEW_REPORT {
            get {
                return ResourceManager.GetString("VIEW_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume:.
        /// </summary>
        public static string VOLUME {
            get {
                return ResourceManager.GetString("VOLUME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock.
        /// </summary>
        public static string WEB_LINK_CLOCK {
            get {
                return ResourceManager.GetString("WEB_LINK_CLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timers.
        /// </summary>
        public static string WEB_LINK_TIMERS {
            get {
                return ResourceManager.GetString("WEB_LINK_TIMERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to offline....
        /// </summary>
        public static string WEB_OFFLINE {
            get {
                return ResourceManager.GetString("WEB_OFFLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekend.
        /// </summary>
        public static string WEEKEND {
            get {
                return ResourceManager.GetString("WEEKEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekend includes Friday.
        /// </summary>
        public static string WEEKEND_INCLUDES_FRIDAY {
            get {
                return ResourceManager.GetString("WEEKEND_INCLUDES_FRIDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seconds.
        /// </summary>
        public static string X_SECONDS {
            get {
                return ResourceManager.GetString("X_SECONDS", resourceCulture);
            }
        }
    }
}
