//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlyT.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnlyT.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bell is active.
        /// </summary>
        internal static string ACTIVE_BELL {
            get {
                return ResourceManager.GetString("ACTIVE_BELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string ADAPTIVE_MODE_NONE {
            get {
                return ResourceManager.GetString("ADAPTIVE_MODE_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-way.
        /// </summary>
        internal static string ADAPTIVE_MODE_ONE_WAY {
            get {
                return ResourceManager.GetString("ADAPTIVE_MODE_ONE_WAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-way.
        /// </summary>
        internal static string ADAPTIVE_MODE_TWO_WAY {
            get {
                return ResourceManager.GetString("ADAPTIVE_MODE_TWO_WAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software version {0}.
        /// </summary>
        internal static string APP_VER {
            get {
                return ResourceManager.GetString("APP_VER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12-hour.
        /// </summary>
        internal static string CLOCK_FORMAT_12 {
            get {
                return ResourceManager.GetString("CLOCK_FORMAT_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12-hour (am/pm).
        /// </summary>
        internal static string CLOCK_FORMAT_12AMPM {
            get {
                return ResourceManager.GetString("CLOCK_FORMAT_12AMPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12-hour (leading zero).
        /// </summary>
        internal static string CLOCK_FORMAT_12Z {
            get {
                return ResourceManager.GetString("CLOCK_FORMAT_12Z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12-hour (leading zero &amp; am/pm).
        /// </summary>
        internal static string CLOCK_FORMAT_12ZAMPM {
            get {
                return ResourceManager.GetString("CLOCK_FORMAT_12ZAMPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24-hour.
        /// </summary>
        internal static string CLOCK_FORMAT_24 {
            get {
                return ResourceManager.GetString("CLOCK_FORMAT_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24-hour (leading zero).
        /// </summary>
        internal static string CLOCK_FORMAT_24Z {
            get {
                return ResourceManager.GetString("CLOCK_FORMAT_24Z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html style=&quot;display:block; height:100%; margin:0; padding:0&quot;&gt;
        ///	&lt;head&gt;
        ///		&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;/&gt;		
        ///		&lt;title&gt;OnlyT Clock&lt;/title&gt;
        ///		&lt;style type=&quot;text/css&quot;&gt;			
        ///			html 
        ///			{
        ///				background: #000000;
        ///			}
        ///			.clockstyle 
        ///			{
        ///				font-family: sans-serif;
        ///				font-weight: bold;
        ///				color: #FFFFFF;
        ///			}
        ///			.clockstyle_yellow
        ///			{
        ///				font-family: sans-serif;
        ///				font-weight: bold;
        ///				color: #FFFF66;
        ///			}
        ///			.clockstyle_green
        ///			{ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClockHtmlTemplate {
            get {
                return ResourceManager.GetString("ClockHtmlTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create folder {0}.
        /// </summary>
        internal static string CREATE_FOLDER_ERROR {
            get {
                return ResourceManager.GetString("CREATE_FOLDER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapted duration.
        /// </summary>
        internal static string DURATION_ADAPTED {
            get {
                return ResourceManager.GetString("DURATION_ADAPTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified duration.
        /// </summary>
        internal static string DURATION_MODIFIED {
            get {
                return ResourceManager.GetString("DURATION_MODIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original duration.
        /// </summary>
        internal static string DURATION_ORIGINAL {
            get {
                return ResourceManager.GetString("DURATION_ORIGINAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analogue.
        /// </summary>
        internal static string FULL_SCREEN_ANALOGUE {
            get {
                return ResourceManager.GetString("FULL_SCREEN_ANALOGUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analogue and Digital.
        /// </summary>
        internal static string FULL_SCREEN_BOTH {
            get {
                return ResourceManager.GetString("FULL_SCREEN_BOTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital.
        /// </summary>
        internal static string FULL_SCREEN_DIGITAL {
            get {
                return ResourceManager.GetString("FULL_SCREEN_DIGITAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bell is inactive.
        /// </summary>
        internal static string INACTIVE_BELL {
            get {
                return ResourceManager.GetString("INACTIVE_BELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midweek.
        /// </summary>
        internal static string MIDWEEK {
            get {
                return ResourceManager.GetString("MIDWEEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ministry - Item 1.
        /// </summary>
        internal static string MINISTRY1 {
            get {
                return ResourceManager.GetString("MINISTRY1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ministry - Item 2.
        /// </summary>
        internal static string MINISTRY2 {
            get {
                return ResourceManager.GetString("MINISTRY2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ministry - Item 3.
        /// </summary>
        internal static string MINISTRY3 {
            get {
                return ResourceManager.GetString("MINISTRY3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string MONITOR_NONE {
            get {
                return ResourceManager.GetString("MONITOR_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available while timer is running!.
        /// </summary>
        internal static string NOT_AVAIL_TIMER_RUNNING {
            get {
                return ResourceManager.GetString("NOT_AVAIL_TIMER_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        internal static string OP_MODE_AUTO {
            get {
                return ResourceManager.GetString("OP_MODE_AUTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File-based.
        /// </summary>
        internal static string OP_MODE_FILE {
            get {
                return ResourceManager.GetString("OP_MODE_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        internal static string OP_MODE_MANUAL {
            get {
                return ResourceManager.GetString("OP_MODE_MANUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Living.
        /// </summary>
        internal static string SECTION_LIVING {
            get {
                return ResourceManager.GetString("SECTION_LIVING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ministry.
        /// </summary>
        internal static string SECTION_MINISTRY {
            get {
                return ResourceManager.GetString("SECTION_MINISTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treasures.
        /// </summary>
        internal static string SECTION_TREASURES {
            get {
                return ResourceManager.GetString("SECTION_TREASURES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekend.
        /// </summary>
        internal static string SECTION_WEEKEND {
            get {
                return ResourceManager.GetString("SECTION_WEEKEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SETTINGS {
            get {
                return ResourceManager.GetString("SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bible Study / Talk.
        /// </summary>
        internal static string TALK_BIBLE_STUDY {
            get {
                return ResourceManager.GetString("TALK_BIBLE_STUDY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concluding Talk.
        /// </summary>
        internal static string TALK_CONCLUDING {
            get {
                return ResourceManager.GetString("TALK_CONCLUDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concluding Comments.
        /// </summary>
        internal static string TALK_CONCLUDING_COMMENTS {
            get {
                return ResourceManager.GetString("TALK_CONCLUDING_COMMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congregation Bible Study.
        /// </summary>
        internal static string TALK_CONG_STUDY {
            get {
                return ResourceManager.GetString("TALK_CONG_STUDY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digging for Spiritual Gems.
        /// </summary>
        internal static string TALK_DIGGING {
            get {
                return ResourceManager.GetString("TALK_DIGGING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Call.
        /// </summary>
        internal static string TALK_INITIAL_CALL {
            get {
                return ResourceManager.GetString("TALK_INITIAL_CALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Living - Part 1.
        /// </summary>
        internal static string TALK_LIVING1 {
            get {
                return ResourceManager.GetString("TALK_LIVING1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Living - Part 2.
        /// </summary>
        internal static string TALK_LIVING2 {
            get {
                return ResourceManager.GetString("TALK_LIVING2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Comments.
        /// </summary>
        internal static string TALK_OPENING_COMMENTS {
            get {
                return ResourceManager.GetString("TALK_OPENING_COMMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Month&apos;s Presentations.
        /// </summary>
        internal static string TALK_PRESENTATIONS {
            get {
                return ResourceManager.GetString("TALK_PRESENTATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Talk.
        /// </summary>
        internal static string TALK_PUBLIC {
            get {
                return ResourceManager.GetString("TALK_PUBLIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bible Reading.
        /// </summary>
        internal static string TALK_READING {
            get {
                return ResourceManager.GetString("TALK_READING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Visit.
        /// </summary>
        internal static string TALK_RV {
            get {
                return ResourceManager.GetString("TALK_RV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Talk.
        /// </summary>
        internal static string TALK_SERVICE {
            get {
                return ResourceManager.GetString("TALK_SERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treasures Talk.
        /// </summary>
        internal static string TALK_TREASURES {
            get {
                return ResourceManager.GetString("TALK_TREASURES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watchtower Study.
        /// </summary>
        internal static string TALK_WT {
            get {
                return ResourceManager.GetString("TALK_WT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekend.
        /// </summary>
        internal static string WEEKEND {
            get {
                return ResourceManager.GetString("WEEKEND", resourceCulture);
            }
        }
    }
}
