//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlyT.Report.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnlyT.Report.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to counsel and commendation.
        /// </summary>
        internal static string COUNSEL {
            get {
                return ResourceManager.GetString("COUNSEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midweek and Weekend Meetings.
        /// </summary>
        internal static string MIDWEEK_AND_WEEKEND_MTGS {
            get {
                return ResourceManager.GetString("MIDWEEK_AND_WEEKEND_MTGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midweek Meetings.
        /// </summary>
        internal static string MIDWEEK_MTGS {
            get {
                return ResourceManager.GetString("MIDWEEK_MTGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting on time.
        /// </summary>
        internal static string ON_TIME {
            get {
                return ResourceManager.GetString("ON_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall Status.
        /// </summary>
        internal static string OVERALL_STATUS {
            get {
                return ResourceManager.GetString("OVERALL_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting overtime by ~{0} minutes.
        /// </summary>
        internal static string OVERTIME_BY {
            get {
                return ResourceManager.GetString("OVERTIME_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting overtime by 1 minute.
        /// </summary>
        internal static string OVERTIME_BY_1 {
            get {
                return ResourceManager.GetString("OVERTIME_BY_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overtime (mins).
        /// </summary>
        internal static string OVERTIME_MINS {
            get {
                return ResourceManager.GetString("OVERTIME_MINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timing Report.
        /// </summary>
        internal static string REPORT_TITLE {
            get {
                return ResourceManager.GetString("REPORT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timing Summary.
        /// </summary>
        internal static string TIMING_SUMMARY {
            get {
                return ResourceManager.GetString("TIMING_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting undertime by ~{0} minutes.
        /// </summary>
        internal static string UNDERTIME_BY {
            get {
                return ResourceManager.GetString("UNDERTIME_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting undertime by 1 minute.
        /// </summary>
        internal static string UNDERTIME_BY_1 {
            get {
                return ResourceManager.GetString("UNDERTIME_BY_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekend Meetings.
        /// </summary>
        internal static string WEEKEND_MTGS {
            get {
                return ResourceManager.GetString("WEEKEND_MTGS", resourceCulture);
            }
        }
    }
}
